services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: talent_base_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:15
    container_name: postgres_database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
